import re
import json
import os

SLOT_BOXES_PATH = 'src/data/slotBoxesData.ts'

# The 22 slots with verified image and audio mappings
SLOT_CONFIGS = [
  {
    "id": "slot-siva-manthiram",
    "slotNumber": 1,
    "title": "Siva Manthiram",
    "subtitle": "சிவ மந்திரம் • Dr. S.P. Balasubrahmanyam Master Devotional",
    "tamilTitle": "சிவ மந்திரம்",
    "imageFileName": "Siva Manthiram [SPB] Final.png",
    "imagePath": "/new%20images/Siva%20Manthiram%20%5BSPB%5D%20Final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Bhairav / Shivaranjani",
    "tala": "Adi Tala",
    "description": "Subam Master Devotional recording of holy Shiva Mantras and Tiruvannamalai Arunachaleswarar sacred chants rendered by S.P.B.",
    "youtubeVideoId": "17mC8Z-xK6c",
    "audioFile": {
      "name": "sav_acd_118_02_om_shivaya.mp3",
      "size": 12446720,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_118_02_om_shivaya.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-siva-sambo",
    "slotNumber": 2,
    "title": "Siva Sambo",
    "subtitle": "சிவ சாம்போ • Kailasa Cosmic Shiva Stotram",
    "tamilTitle": "சிவ சாம்போ சிவ சாம்போ",
    "imageFileName": "Siva Sambo [SPB] Final.png",
    "imagePath": "/new%20images/Siva%20Sambo%20%5BSPB%5D%20Final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Revati",
    "tala": "Rupaka Tala",
    "description": "Electrifying vocal rendition of Siva Sambo by Dr. S.P.B with mridangam and sacred dholak rhythms.",
    "youtubeVideoId": "aG3jT9Yq8wA",
    "audioFile": {
      "name": "sav_acd_107_05_deepa_dharisanam.mp3",
      "size": 5578752,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_107_05_deepa_dharisanam.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-siva-shivaya",
    "slotNumber": 3,
    "title": "Siva Shivaya",
    "subtitle": "சிவ சிவாய போற்றி • Agni Lingam Tiruvannamalai Special",
    "tamilTitle": "சிவ சிவாய போற்றி",
    "imageFileName": "Siva Shivaya [SPB] Final.png",
    "imagePath": "/new%20images/Siva%20Shivaya%20%5BSPB%5D%20Final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Bhairavi",
    "tala": "Adi Tala",
    "description": "Divine, peaceful chant of Siva Shivaya evoking the holy flames of Karthigai Deepam.",
    "youtubeVideoId": "17mC8Z-xK6c",
    "audioFile": {
      "name": "sav_acd_140_05_vinnai_alantha.mp3",
      "size": 6427648,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_140_05_vinnai_alantha.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-siva-siva-sankara",
    "slotNumber": 4,
    "title": "Siva Siva Sankara",
    "subtitle": "சிவ சிவ சங்கரா • Cosmic Nataraja & Arunachala Stotra",
    "tamilTitle": "சிவ சிவ சங்கரா",
    "imageFileName": "Siva Siva Sankara  [SPB] FINAL.png",
    "imagePath": "/new%20images/Siva%20Siva%20Sankara%20%20%5BSPB%5D%20FINAL.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Shivaranjani / Mohanam",
    "tala": "Adi Tala",
    "description": "One of Subam Audio’s most legendary Dr. S.P.B Shiva hits, revered across Tamil Nadu.",
    "youtubeVideoId": "3mY2e8XgR3o",
    "audioFile": {
      "name": "sav_acd_140_08_siva_siva_yendru.mp3",
      "size": 6249472,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_140_08_siva_siva_yendru.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-siva-yogam",
    "slotNumber": 5,
    "title": "Siva Yogam",
    "subtitle": "சிவ யோகம் • Deep Meditation & Arunachala Dhyana Suite",
    "tamilTitle": "சிவ யோகம்",
    "imageFileName": "Siva Yogam  [SPB] Final.png",
    "imagePath": "/new%20images/Siva%20Yogam%20%20%5BSPB%5D%20Final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Charukesi",
    "tala": "Adi Tala (Slow)",
    "description": "Sublime meditative soundscape and prayer for spiritual upliftment and inner peace.",
    "youtubeVideoId": "aG3jT9Yq8wA",
    "audioFile": {
      "name": "sav_acd_140_06_arunachalamae_annamalai.mp3",
      "size": 7204864,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_140_06_arunachalamae_annamalai.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-srinivasa-namo-namo",
    "slotNumber": 6,
    "title": "Srinivasa Namo Namo",
    "subtitle": "ஸ்ரீனிவாசா நமோ நமோ • Tirupati Venkateswara Golden Anthem",
    "tamilTitle": "ஸ்ரீனிவாசா நமோ நமோ",
    "imageFileName": "Srinivasa namo namo  [SPB] final.png",
    "imagePath": "/new%20images/Srinivasa%20namo%20namo%20%20%5BSPB%5D%20final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "PERUMAL_VENKATESWARA",
    "deityTamilName": "பெருமாள் & திருப்பதி வெங்கடேஸ்வரா",
    "categoryName": "Perumal & Venkateswara",
    "raga": "Kalyani / Sindhu Bhairavi",
    "tala": "Adi Tala",
    "description": "Soul-stirring invocation to Lord Venkateswara of the Seven Hills with grand orchestral bells.",
    "youtubeVideoId": "a_Venkatesa_SPB",
    "audioFile": {
      "name": "sav_acd_111_05_thirumalai_vasa.mp3",
      "size": 6787072,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_111_05_thirumalai_vasa.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-srinivasaa",
    "slotNumber": 7,
    "title": "Srinivasaa Govinda",
    "subtitle": "ஸ்ரீனிவாஸா கோவிந்தா • Tirumala Balaji Suprabhata Stuthi",
    "tamilTitle": "ஸ்ரீனிவாஸா கோவிந்தா",
    "imageFileName": "Srinivasaa [SPB] Final.png",
    "imagePath": "/new%20images/Srinivasaa%20%5BSPB%5D%20Final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "PERUMAL_VENKATESWARA",
    "deityTamilName": "பெருமாள் & திருப்பதி வெங்கடேஸ்வரா",
    "categoryName": "Perumal & Venkateswara",
    "raga": "Mohanam",
    "tala": "Adi Tala",
    "description": "Melodious chant celebrating Lord Srinivasa with conch resonance and classical violin.",
    "youtubeVideoId": "spb_tirumala_balaji",
    "audioFile": {
      "name": "sav_acd_124_01_namo_venkatesa_hari_namo.mp3",
      "size": 11261952,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_124_01_namo_venkatesa_hari_namo.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-tamil-sivashthuthi",
    "slotNumber": 8,
    "title": "Tamil Sivashthuthi",
    "subtitle": "தமிழ் சிவஸ்துதி • Sacred Tamil Sthothiram & Thevaram Rendition",
    "tamilTitle": "தமிழ் சிவஸ்துதி",
    "imageFileName": "Tamil Sivashthuthi [SPB] PNG.png",
    "imagePath": "/new%20images/Tamil%20Sivashthuthi%20%5BSPB%5D%20PNG.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Hamsadhwani / Kapi",
    "tala": "Adi Tala",
    "description": "Authentic Tamil verses praising Lord Shiva with pristine diction by Dr. S.P.B.",
    "youtubeVideoId": "spb_sivastuthi",
    "audioFile": {
      "name": "sav_acd_140_03_moondru_thalam.mp3",
      "size": 2789376,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_140_03_moondru_thalam.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-vaepilai-kolam",
    "slotNumber": 9,
    "title": "Aadhi Sakthi",
    "subtitle": "ஆதி சக்தி • Adhiyae Kaaliyae Devotional Classic",
    "tamilTitle": "ஆதி சக்தி",
    "imageFileName": "Aadhi Sakthi [SPB] PNG FINAL.png",
    "imagePath": "/new%20images/Aadhi%20Sakthi%20%5BSPB%5D%20PNG%20FINAL.png",
    "singer": "Mahanadhi Shobana",
    "deity": "AMMAN_SHAKTHI",
    "deityTamilName": "அம்மன் & ஓம்சக்தி / மாரியம்மன்",
    "categoryName": "Amman & Shakthi",
    "raga": "Sindhu Bhairavi / Folk",
    "tala": "Roopaka / Fast Urumee",
    "description": "Evergreen Amman blockbuster sung by Mahanadhi Shobana invoking Mother Adhiparasakthi.",
    "youtubeVideoId": "shobana_amman_veppilai",
    "audioFile": {
      "name": "sav_acd_102_01_adhiyae_kaaliyae.mp3",
      "size": 5872000,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_102_01_adhiyae_kaaliyae.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-vedha-sakthi",
    "slotNumber": 10,
    "title": "Vedha Sakthi",
    "subtitle": "வேத சக்தி • Melmaruvathur & Adhiparasakthi Mahima",
    "tamilTitle": "வேத சக்தி",
    "imageFileName": "Om Sakthi [SPB] Final.png",
    "imagePath": "/new%20images/Om%20Sakthi%20%5BSPB%5D%20Final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "AMMAN_SHAKTHI",
    "deityTamilName": "அம்மன் & ஓம்சக்தி / மாரியம்மன்",
    "categoryName": "Amman & Shakthi",
    "raga": "Kalyani",
    "tala": "Adi Tala",
    "description": "Dr. S.P.B sings in praise of supreme Mother Shakthi with powerful Vedic mantras and divine chords.",
    "youtubeVideoId": "spb_om_sakthi",
    "audioFile": {
      "name": "sav_acd_120_01_aatha_angali.mp3",
      "size": 5410816,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_120_01_aatha_angali.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-velmuruga",
    "slotNumber": 11,
    "title": "Velmuruga",
    "subtitle": "வேல்முருகா வெற்றிவேல் • Palani & Tiruchendur Kavadi Anthem",
    "tamilTitle": "வேல்முருகா வெற்றிவேல்",
    "imageFileName": "playlist_murugan_kandha_1787913891920.jpg",
    "imagePath": "/images/playlist_murugan_kandha_1787913891920.jpg",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "MURUGAN",
    "deityTamilName": "முருகன் & கந்த சஷ்டி பாடல்கள்",
    "categoryName": "Murugan Padalgal",
    "raga": "Shanmukhapriya",
    "tala": "Tisra Gati / Adi Tala",
    "description": "High-energy Kavadi Sindhu and Vel anthem celebrating the triumph of Lord Murugan.",
    "youtubeVideoId": "spb_velmuruga",
    "audioFile": {
      "name": "sav_acd_115_01_vetri_vadivelava.mp3",
      "size": 12603392,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_115_01_vetri_vadivelava.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-venkatesh",
    "slotNumber": 12,
    "title": "Venkatesha Perumal",
    "subtitle": "வேங்கடேசா பெருமாள் • Tirumala Govinda Namavali",
    "tamilTitle": "வேங்கடேசா பெருமாள்",
    "imageFileName": "Venkatesh [SPB] PNG.png",
    "imagePath": "/new%20images/Venkatesh%20%5BSPB%5D%20PNG.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "PERUMAL_VENKATESWARA",
    "deityTamilName": "பெருமாள் & திருப்பதி வெங்கடேஸ்வரா",
    "categoryName": "Perumal & Venkateswara",
    "raga": "Bilahari",
    "tala": "Adi Tala",
    "description": "Classic Perumal devotion capturing the grandeur of Lord Venkateswara with sanctum bell chimes.",
    "youtubeVideoId": "spb_venkateswara",
    "audioFile": {
      "name": "sav_acd_124_04_nenjae_nenjae.mp3",
      "size": 5159936,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_124_04_nenjae_nenjae.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-annamalai-arohara",
    "slotNumber": 13,
    "title": "Annamalai Arohara",
    "subtitle": "அண்ணாமலைக்கு அரோகரா • Tiruvannamalai Deepam Anthem",
    "tamilTitle": "அண்ணாமலைக்கு அரோகரா",
    "imageFileName": "Siva Manthiram [SPB] Final.png",
    "imagePath": "/new%20images/Siva%20Manthiram%20%5BSPB%5D%20Final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Bhairav",
    "tala": "Adi Tala",
    "description": "The thunderous cry of devotion during Tiruvannamalai Girivalam echoing Arunachala Arohara.",
    "youtubeVideoId": "17mC8Z-xK6c",
    "audioFile": {
      "name": "sav_acd_118_04_annamalaiyalum.mp3",
      "size": 3985408,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_118_04_annamalaiyalum.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-arunachalam",
    "slotNumber": 14,
    "title": "Arunachalam",
    "subtitle": "அருணாசலம் சிவ அருணாசலம் • Holy Mountain Chants",
    "tamilTitle": "அருணாசலம் சிவ அருணாசலம்",
    "imageFileName": "Arunachalam [SPB] PNG.png",
    "imagePath": "/new%20images/Arunachalam%20%5BSPB%5D%20PNG.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Revati",
    "tala": "Adi Tala",
    "description": "Solemn prayer dedicated to the sacred hill of Arunachala, the physical incarnation of Lord Shiva.",
    "youtubeVideoId": "aG3jT9Yq8wA",
    "audioFile": {
      "name": "sav_acd_118_01_arunachalanae.mp3",
      "size": 22083584,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_118_01_arunachalanae.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-girivalam",
    "slotNumber": 15,
    "title": "Girivalam",
    "subtitle": "கிரிவலம் சிறப்பு • 14 km Sacred Circumambulation Suite",
    "tamilTitle": "கிரிவலம் சிறப்பு",
    "imageFileName": "Girivalam [SPB] PNG.png",
    "imagePath": "/new%20images/Girivalam%20%5BSPB%5D%20PNG.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Mohanam",
    "tala": "Adi Tala",
    "description": "Guiding pilgrims step-by-step around the 14-kilometer sacred path of Arunachala.",
    "youtubeVideoId": "17mC8Z-xK6c",
    "audioFile": {
      "name": "sav_acd_107_06_malaivalam.mp3",
      "size": 6941696,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_107_06_malaivalam.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-ayyapa-pallikattu",
    "slotNumber": 16,
    "title": "Pallikattu Sabarimalaikku",
    "subtitle": "பள்ளிக்கட்டு சபரிமலைக்கு • Ayyappa Swamy Golden Pilgrimage",
    "tamilTitle": "பள்ளிக்கட்டு சபரிமலைக்கு",
    "imageFileName": "Pallikattu [SPB] FINAL.png",
    "imagePath": "/new%20images/Pallikattu%20%5BSPB%5D%20FINAL.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "AYYAPPAN",
    "deityTamilName": "ஐயப்பன் & சபரிமலை பாடல்கள்",
    "categoryName": "Ayyappan & Sabarimala",
    "raga": "Kapi / Folk",
    "tala": "Adi Tala",
    "description": "The golden anthem of Sabarimala devotees heading with Irumudi kattu and holy chants.",
    "youtubeVideoId": "spb_ayyappan_pallikattu",
    "audioFile": {
      "name": "sav_acd_126_04_saranam_saranam.mp3",
      "size": 12017664,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_126_04_saranam_saranam.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-gananaatha",
    "slotNumber": 17,
    "title": "Gananaatha Vinayaga",
    "subtitle": "கணநாதா விநாயகனே • First Auspicious Invocation",
    "tamilTitle": "கணநாதா விநாயகனே",
    "imageFileName": "Gananaatha [SPB] PNG.png",
    "imagePath": "/new%20images/Gananaatha%20%5BSPB%5D%20PNG.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "VINAYAGAR",
    "deityTamilName": "விநாயகர் & கணபதி பாடல்கள்",
    "categoryName": "Vinayagar Padalgal",
    "raga": "Hamsadhwani",
    "tala": "Adi Tala",
    "description": "Magnificent opening prayer invoking Lord Ganesha to remove obstacles and bestow prosperity.",
    "youtubeVideoId": "spb_vinayagar",
    "audioFile": {
      "name": "sav_acd_122_04_gananatha_gananatha.mp3",
      "size": 11272192,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_122_04_gananatha_gananatha.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-anjaneya",
    "slotNumber": 18,
    "title": "Anjaneya Veeranjaneya",
    "subtitle": "ஆஞ்சநேயா வீர ஆஞ்சநேயா • Bajrangbali Courage Anthem",
    "tamilTitle": "ஆஞ்சநேயா வீர ஆஞ்சநேயா",
    "imageFileName": "hanuman.jpg",
    "imagePath": "/images/hanuman.jpg",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANJANEYAR_HANUMAN",
    "deityTamilName": "ஆஞ்சநேயர் & ஜெய ஹனுமான்",
    "categoryName": "Anjaneyar & Hanuman",
    "raga": "Gambheera Nattai",
    "tala": "Khanda Chapu",
    "description": "Dynamic composition celebrating the heroic courage and unwavering loyalty of Sri Hanuman.",
    "youtubeVideoId": "spb_hanuman",
    "audioFile": {
      "name": "sav_acd_124_06_sanivaara_poojai.mp3",
      "size": 11325440,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_124_06_sanivaara_poojai.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-guru-raghavendra",
    "slotNumber": 19,
    "title": "Guru Ragavendhira",
    "subtitle": "குரு ராகவேந்திரா • Mantralayam Divine Grace",
    "tamilTitle": "குரு ராகவேந்திரா",
    "imageFileName": "guru_raghavendra_1787739997358.jpg",
    "imagePath": "/images/guru_raghavendra_1787739997358.jpg",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "குரு ராகவேந்திரர் & மகா ஞானிகள்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Kalyani",
    "tala": "Adi Tala",
    "description": "Devotional tribute to Sri Guru Raghavendra Swamy of Mantralayam, granting devotees solace.",
    "youtubeVideoId": "spb_raghavendra",
    "audioFile": {
      "name": "sav_acd_111_01_namo_namo_narayana.mp3",
      "size": 12194816,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_111_01_namo_namo_narayana.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-pournami-poojai",
    "slotNumber": 20,
    "title": "Pournami Poojai",
    "subtitle": "பௌர்ணமி பூஜை • Full Moon Goddess Shakthi Special",
    "tamilTitle": "பௌர்ணமி பூஜை",
    "imageFileName": "POURNAMI POOJAI [MAGHANADHI SHOBANA] PNG.png",
    "imagePath": "/new%20images/POURNAMI%20POOJAI%20%5BMAGHANADHI%20SHOBANA%5D%20PNG.png",
    "singer": "Mahanadhi Shobana",
    "deity": "AMMAN_SHAKTHI",
    "deityTamilName": "அம்மன் & ஓம்சக்தி / மாரியம்மன்",
    "categoryName": "Amman & Shakthi",
    "raga": "Sindhu Bhairavi",
    "tala": "Adi Tala",
    "description": "Auspicious full moon Amman worship song praising the mother of the universe with glowing lamps.",
    "youtubeVideoId": "shobana_pournami",
    "audioFile": {
      "name": "sav_acd_102_06_sandhana_mari.mp3",
      "size": 6688768,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_102_06_sandhana_mari.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-108-thirupathi",
    "slotNumber": 21,
    "title": "108 Thirupathi Divya Desam",
    "subtitle": "108 திருப்பதி திவ்ய தேசம் • Vaishnava Holy Shrines",
    "tamilTitle": "108 திருப்பதி திவ்ய தேசம்",
    "imageFileName": "108 Thirupathi [SPB] Final.png",
    "imagePath": "/new%20images/108%20Thirupathi%20%5BSPB%5D%20Final.png",
    "singer": "Dr. S.P. Balasubrahmanyam",
    "deity": "PERUMAL_VENKATESWARA",
    "deityTamilName": "பெருமாள் & திருப்பதி வெங்கடேஸ்வரா",
    "categoryName": "Perumal & Venkateswara",
    "raga": "Charukesi",
    "tala": "Adi Tala",
    "description": "Glorious musical voyage through the 108 Sacred Divya Desams rendered by S.P.B.",
    "youtubeVideoId": "spb_108_thirupathi",
    "audioFile": {
      "name": "sav_acd_124_03_thirumalai_iraivaa.mp3",
      "size": 4392960,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_124_03_thirumalai_iraivaa.mp3",
      "uploadedAt": 1741760000000
    }
  },
  {
    "id": "slot-shivaya-namaha-unnikrishnan",
    "slotNumber": 22,
    "title": "Shivaya Namaha Om Shivaya Namaha",
    "subtitle": "சிவாய நமஹ ஓம் சிவாய நமஹ • P. Unnikrishnan Classic",
    "tamilTitle": "சிவாய நமஹ ஓம் சிவாய நமஹ",
    "imageFileName": "Shivaya Namaha Om Shivaya Namaha [Unnikrishnan] Final.png",
    "imagePath": "/new%20images/Shivaya%20Namaha%20Om%20Shivaya%20Namaha%20%5BUnnikrishnan%5D%20Final.png",
    "singer": "P. Unnikrishnan",
    "deity": "ANNAMALAIYAR_SIVAN",
    "deityTamilName": "அண்ணாமலையார் & சிவன்",
    "categoryName": "Annamalaiyar & Sivan",
    "raga": "Revati / Yaman",
    "tala": "Adi Tala (Deep Meditative)",
    "description": "Timeless peaceful chanting of the Panchakshara mantra by Carnatic maestro P. Unnikrishnan.",
    "youtubeVideoId": "unnikrishnan_om_namah",
    "audioFile": {
      "name": "sav_acd_140_07_anbae_sivam.mp3",
      "size": 5840896,
      "type": "audio/mpeg",
      "url": "/audio/sav_acd_140_07_anbae_sivam.mp3",
      "uploadedAt": 1741760000000
    }
  }
]

ts_content = f"""import {{ DevotionalSlot, SacredDeity, Song }} from '../types';

export const INITIAL_DEVOTIONAL_SLOTS: DevotionalSlot[] = {json.dumps(SLOT_CONFIGS, indent=2)};

/**
 * Converts a slot box to a full Song model for standard playback across the app
 */
export function slotToSong(slot: DevotionalSlot): Song {{
  return {{
    id: slot.id,
    title: slot.title,
    subtitle: slot.subtitle || `${{slot.tamilTitle || slot.title}} • ${{slot.singer}}`,
    tamilTitle: slot.tamilTitle,
    description: slot.description || `${{slot.title}} devotional master track by ${{slot.singer}}.`,
    coverImage: slot.imagePath,
    previewAudioUrl: slot.audioFile ? slot.audioFile.url : '/audio-preview/shiva-tandava',
    customUploadedAudioUrl: slot.audioFile?.url,
    customFileName: slot.audioFile?.name,
    customFileSize: slot.audioFile?.size,
    customUploadedAt: slot.audioFile ? new Date(slot.audioFile.uploadedAt).toISOString() : undefined,
    price: 49,
    duration: slot.audioFile?.duration ? `${{Math.floor(slot.audioFile.duration / 60)}}:${{(slot.audioFile.duration % 60).toString().padStart(2, '0')}}` : '06:15',
    durationSeconds: slot.audioFile?.duration || 375,
    language: 'Tamil',
    categoryId: slot.categoryName.toLowerCase().includes('sivan') ? 'cat-sivan' : slot.categoryName.toLowerCase().includes('perumal') ? 'cat-perumal' : slot.categoryName.toLowerCase().includes('murugan') ? 'cat-murugan' : 'cat-amman',
    categoryName: slot.categoryName,
    deity: slot.deity,
    deityTamilName: slot.deityTamilName,
    songType: 'DEVOTIONAL_HIT',
    songTypeLabel: slot.tamilTitle || 'சுபம் மாஸ்டர் பாடல்',
    releaseDate: '2026-03-01',
    status: 'PUBLISHED',
    playCount: 520000,
    downloadCount: 18400,
    featured: true,
    trending: true,
    raga: slot.raga || 'Bhairav',
    tala: slot.tala || 'Adi Tala',
    youtubeVideoId: slot.youtubeVideoId || '17mC8Z-xK6c',
    youtubeUrl: slot.youtubeUrl || `https://youtube.com/watch?v=${{slot.youtubeVideoId || '17mC8Z-xK6c'}}`,
    credits: {{
      singer: slot.singer,
      lyricist: 'Traditional Devotional',
      composer: 'Subam Audio Vision Music Guild',
      musicDirector: 'Subam Audio Vision',
      studio: 'Subam Digital Audio Studio Tiruvannamalai',
      producer: 'Subam Audio Vision (Est. 1997)'
    }},
    isSlotBox: true,
    slotNumber: slot.slotNumber,
    trackNumber: slot.trackNumber,
    albumCode: slot.albumCode,
    albumTitle: slot.albumTitle,
    fullAudioUrl: slot.audioFile ? slot.audioFile.url : undefined,
  }};
}}
"""

with open(SLOT_BOXES_PATH, 'w') as f:
    f.write(ts_content)

print("Updated src/data/slotBoxesData.ts")
